use Lithe::{
    fmc_core::Term,
    interpreter::{Lexer, Parser},
};

fn parse_program_ast(source: &str) -> Term {
    let result = Lexer::new(source.to_string()).tokenise();
    assert!(
        result.errors.is_empty(),
        "lexer errors in roundtrip test: {:?}",
        result.errors
    );

    Parser::new(result.tokens).parse().unwrap()
}

fn parse_raw_fmc_term(source: &str) -> Term {
    parse_program_ast(&format!("\\{source}\\;"))
}

fn assert_ast_roundtrip(program: &str) {
    let original = parse_program_ast(program).expand_operations();
    let printed = original.to_string();
    let reparsed = parse_raw_fmc_term(&printed);

    assert_eq!(reparsed, original, "roundtrip failed for `{printed}`");
}

// These tests were generated by ChatGPT.
#[test]
fn roundtrips_operator_heavy_program_ast_through_raw_fmc() {
    let program = r#"
        a := 8;
        b := 3;

        print $a + $b;
        print $a - $b;
        print -$b;
        print $a * $b;
        print int ($a / $b);
        print $a % $b;
        print !false;
        print ($a > $b) && ($a != 0);
        print ($a < $b) || false;
    "#;

    assert_ast_roundtrip(program);
}

#[test]
fn roundtrips_blocks_and_loops_through_raw_fmc() {
    let program = r#"
        a := 3;
        while ($a > 0) {
            print $a;
            a := $a - 1;
        }
    "#;

    assert_ast_roundtrip(program);
}

#[test]
fn roundtrips_embedded_fmc_and_casts_through_raw_fmc() {
    let program = r#"
        f := \out<x>.[x].#\;
        print int (\rnd_f<x>.[x].#\ * 5);
        print \[true].f\;
    "#;

    assert_ast_roundtrip(program);
}

#[test]
fn roundtrips_primes_program() {
    let program = r#"
        n := input;
        i := 2;

        while ($i <= $n) {
            isprime := true;

            j := 2;
            while ($j <= $i/2) {
                if ($i % $j == 0) {
                    isprime := false;
                    break;
                }
                j := $j + 1;
            }

            if ($isprime) {
                print $i;
            }

            i := $i + 1;
        }
    "#;

    assert_ast_roundtrip(program);
}
