use lithe::{
    fmc_core::Term,
    interpreter::Interpreter,
    machines::{
        KrivineMachine, Machine, StackMachine,
        machine::{MachineType, StepResult},
        runtime_io::parse_input_term,
    },
};
use std::fs;

fn compile_program(program: &str, rnd: bool) -> lithe::fmc_core::Term {
    Interpreter::new(true, MachineType::Stack)
        .compile(program.to_string(), false, rnd)
        .unwrap()
}

fn run_stack(program: &str) -> (StepResult, Vec<String>) {
    let term = compile_program(program, false);
    let mut machine = StackMachine::new(term);
    machine.set_silent(true);
    let result = machine.run(false);
    (result, machine.output().to_vec())
}

fn run_krivine(program: &str) -> (StepResult, Vec<String>) {
    let term = compile_program(program, false);
    let mut machine = KrivineMachine::new(term);
    machine.set_silent(true);
    let result = machine.run(false);
    (result, machine.output().to_vec())
}

fn run_stack_with_input(program: &str, inputs: Vec<Term>) -> (StepResult, Vec<String>) {
    let term = compile_program(program, false);
    let mut machine = StackMachine::new(term);
    machine.set_silent(true);
    machine.seed_input(inputs);
    let result = machine.run(false);
    (result, machine.output().to_vec())
}

fn run_krivine_with_input(program: &str, inputs: Vec<Term>) -> (StepResult, Vec<String>) {
    let term = compile_program(program, false);
    let mut machine = KrivineMachine::new(term);
    machine.set_silent(true);
    machine.seed_input(inputs);
    let result = machine.run(false);
    (result, machine.output().to_vec())
}

fn run_stack_with_rnd(program: &str) -> (StepResult, Vec<String>) {
    let term = compile_program(program, true);
    let mut machine = StackMachine::new(term);
    machine.set_silent(true);
    let result = machine.run(false);
    (result, machine.output().to_vec())
}

fn run_krivine_with_rnd(program: &str) -> (StepResult, Vec<String>) {
    let term = compile_program(program, true);
    let mut machine = KrivineMachine::new(term);
    machine.set_silent(true);
    let result = machine.run(false);
    (result, machine.output().to_vec())
}

fn assert_outputs_on_both_machines(program: &str, expected: &[&str]) {
    let (stack_result, stack_output) = run_stack_with_rnd(program);
    let (krivine_result, krivine_output) = run_krivine_with_rnd(program);

    assert_eq!(stack_result, StepResult::Stop);
    assert_eq!(krivine_result, StepResult::Stop);
    assert_eq!(stack_output, expected);
    assert_eq!(krivine_output, expected);
}

// These tests were generated by ChatGPT.
#[test]
fn arithmetic_and_assignment_operators_work() {
    let program = r#"
        a := 8;
        b := 3;

        print $a + $b;
        print $a - $b;
        print $a * $b;
        print $a % $b;
        print int ($a / $b);
        print -$b;
    "#;

    assert_outputs_on_both_machines(program, &["11", "5", "24", "2", "2", "-3"]);
}

#[test]
fn comparison_operators_work() {
    let program = r#"
        print 2 < 3;
        print 3 > 2;
        print 3 <= 3;
        print 4 >= 4;
        print 5 == 5;
        print 5 != 4;
        print (7 / 2) > 3;
    "#;

    assert_outputs_on_both_machines(
        program,
        &["true", "true", "true", "true", "true", "true", "true"],
    );
}

#[test]
fn logical_operators_work() {
    let program = r#"
        print !false;
        print true && false;
        print true || false;
    "#;

    assert_outputs_on_both_machines(program, &["true", "false", "true"]);
}

#[test]
fn rnd_bool_outputs_a_boolean_on_both_machines() {
    let program = r#"
        random_bool := rnd_bool();
        print $random_bool;
    "#;

    let (stack_result, stack_output) = run_stack_with_rnd(program);
    let (krivine_result, krivine_output) = run_krivine_with_rnd(program);

    assert_eq!(stack_result, StepResult::Stop);
    assert_eq!(krivine_result, StepResult::Stop);
    assert_eq!(stack_output.len(), 1);
    assert_eq!(krivine_output.len(), 1);
    assert!(matches!(stack_output[0].as_str(), "true" | "false"));
    assert!(matches!(krivine_output[0].as_str(), "true" | "false"));
}

#[test]
fn rnd_int_outputs_an_inclusive_integer_range_on_both_machines() {
    let program = r#"
        random_int := rnd_int(1 + 1, 3 * 2);
        print $random_int;
    "#;

    let (stack_result, stack_output) = run_stack_with_rnd(program);
    let (krivine_result, krivine_output) = run_krivine_with_rnd(program);

    assert_eq!(stack_result, StepResult::Stop);
    assert_eq!(krivine_result, StepResult::Stop);
    assert_eq!(stack_output.len(), 1);
    assert_eq!(krivine_output.len(), 1);

    let stack_value: i32 = stack_output[0].parse().unwrap();
    let krivine_value: i32 = krivine_output[0].parse().unwrap();

    assert!((2..=6).contains(&stack_value));
    assert!((2..=6).contains(&krivine_value));
}

#[test]
fn multi_argument_function_calls_work_on_both_machines() {
    let program = r#"
        fn add(low, high) {
            return $low + $high;
        }

        result := add(2, 6);
        print $result;
    "#;

    assert_outputs_on_both_machines(program, &["8"]);
}

#[test]
fn multi_parameter_functions_can_call_other_functions() {
    let program = r#"
        fn add(a, b) {
            return $a + $b;
        }

        fn combine(a, b, c) {
            return add(add($a, $b), $c);
        }

        print combine(1, 2, 3);
    "#;

    assert_outputs_on_both_machines(program, &["6"]);
}

#[test]
fn parameter_shadowing_between_functions_is_hygienic() {
    let program = r#"
        fn id(x) {
            return $x;
        }

        fn reuse_names(x) {
            y := id($x + 1);
            return id($y);
        }

        print reuse_names(4);
    "#;

    assert_outputs_on_both_machines(program, &["5"]);
}

#[test]
fn if_else_branches_and_nested_return_work() {
    let program = r#"
        fn classify(n) {
            if ($n > 0) {
                if ($n > 2) {
                    return 30;
                }
                return 20;
            } else {
                return 10;
            }
        }

        print classify(5);
        print classify(1);
        print classify(0);
    "#;

    assert_outputs_on_both_machines(program, &["30", "20", "10"]);
}

#[test]
fn while_loop_can_run_zero_or_multiple_iterations() {
    let program = r#"
        a := 0;
        while ($a > 0) {
            print 99;
        }

        b := 3;
        while ($b > 0) {
            print $b;
            b := $b - 1;
        }
    "#;

    assert_outputs_on_both_machines(program, &["3", "2", "1"]);
}

#[test]
fn do_while_loop_runs_body_before_checking_condition() {
    let program = r#"
        a := 0;
        do {
            print $a;
            a := $a + 1;
        } while ($a < 3)

        b := 0;
        do {
            print 10;
        } while ($b > 0)
    "#;

    assert_outputs_on_both_machines(program, &["0", "1", "2", "10"]);
}

#[test]
fn break_exits_only_the_current_loop() {
    let program = r#"
        i := 0;
        while ($i < 3) {
            j := 0;
            while ($j < 3) {
                print $i * 10 + $j;
                break;
            }
            i := $i + 1;
        }
    "#;

    assert_outputs_on_both_machines(program, &["0", "10", "20"]);
}

#[test]
fn recursion_with_multiple_parameters_works_on_both_machines() {
    let program = r#"
        fn sum_to(n, acc) {
            if ($n == 0) {
                return $acc;
            }

            return sum_to($n - 1, $acc + $n);
        }

        print sum_to(4, 0);
    "#;

    assert_outputs_on_both_machines(program, &["10"]);
}

#[test]
#[ignore = "top-level mutual recursion is not supported yet"]
fn mutual_recursion_works_on_both_machines() {
    let program = r#"
        fn is_even(n) {
            if ($n == 0) {
                return true;
            }

            return is_odd($n - 1);
        }

        fn is_odd(n) {
            if ($n == 0) {
                return false;
            }

            return is_even($n - 1);
        }

        print is_even(4);
        print is_odd(4);
        print is_even(3);
    "#;

    assert_outputs_on_both_machines(program, &["true", "false", "false"]);
}

#[test]
fn fibonacci_program_runs_on_both_machines() {
    let program = fs::read_to_string("fib.lithe").unwrap();
    let (stack_result, stack_output) = run_stack(&program);
    let (krivine_result, krivine_output) = run_krivine(&program);

    assert_eq!(stack_result, StepResult::Stop);
    assert_eq!(krivine_result, StepResult::Stop);
    assert_eq!(stack_output, ["8"]);
    assert_eq!(krivine_output, ["8"]);
}

#[test]
fn primes_program_runs_on_both_machines() {
    let program = fs::read_to_string("primes.lithe").unwrap();
    let input = parse_input_term("10").unwrap();

    let (stack_result, stack_output) = run_stack_with_input(&program, vec![input.clone()]);
    let (krivine_result, krivine_output) = run_krivine_with_input(&program, vec![input]);

    assert_eq!(stack_result, StepResult::Stop);
    assert_eq!(krivine_result, StepResult::Stop);
    assert_eq!(stack_output, ["2", "3", "5", "7"]);
    assert_eq!(krivine_output, ["2", "3", "5", "7"]);
}
