use std::io;

use rand::{random, random_bool};

use crate::fmc_core::{Choice, Term, choice::Constant};

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Number {
    Integer(i32),
    Float(f32),
}

impl Number {
    pub fn trunc_to_int(self) -> i32 {
        match self {
            Number::Integer(value) => value,
            Number::Float(value) => value as i32,
        }
    }

    #[allow(clippy::should_implement_trait)]
    pub fn add(self, other: Number) -> Number {
        match (self, other) {
            (Number::Integer(left), Number::Integer(right)) => Number::Integer(left + right),
            (left, right) => Number::Float(left.as_f32() + right.as_f32()),
        }
    }

    pub fn subtract(self, other: Number) -> Number {
        match (self, other) {
            (Number::Integer(left), Number::Integer(right)) => Number::Integer(left - right),
            (left, right) => Number::Float(left.as_f32() - right.as_f32()),
        }
    }

    pub fn multiply(self, other: Number) -> Number {
        match (self, other) {
            (Number::Integer(left), Number::Integer(right)) => Number::Integer(left * right),
            (left, right) => Number::Float(left.as_f32() * right.as_f32()),
        }
    }

    pub fn divide(self, other: Number) -> Number {
        Number::Float(self.as_f32() / other.as_f32())
    }

    pub fn modulo(self, other: Number) -> Number {
        match (self, other) {
            (Number::Integer(left), Number::Integer(right)) => Number::Integer(left % right),
            (left, right) => Number::Float(left.as_f32() % right.as_f32()),
        }
    }

    pub fn as_f32(self) -> f32 {
        match self {
            Number::Integer(value) => value as f32,
            Number::Float(value) => value,
        }
    }
}

pub fn parse_input_term(text: &str) -> Option<Term> {
    let trimmed = text.trim();

    if trimmed == "true" {
        Some(Term::Choice(Choice::Constant(Constant::Boolean(true))))
    } else if trimmed == "false" {
        Some(Term::Choice(Choice::Constant(Constant::Boolean(false))))
    } else if let Ok(num) = trimmed.parse::<i32>() {
        Some(Term::Choice(Choice::Constant(Constant::Integer(num))))
    } else {
        None
    }
}

pub fn read_input_term() -> Option<Term> {
    let mut buffer = String::new();
    io::stdin().read_line(&mut buffer).ok()?;
    parse_input_term(&buffer)
}

pub fn random_bool_term() -> Term {
    Term::Choice(Choice::Constant(Constant::Boolean(random_bool(0.5))))
}

pub fn random_float_term() -> Term {
    Term::Choice(Choice::Constant(Constant::Float(random::<f32>())))
}

pub fn term_to_number(term: Term) -> Option<Number> {
    match term {
        Term::Choice(Choice::Constant(Constant::Integer(value))) => Some(Number::Integer(value)),
        Term::Choice(Choice::Constant(Constant::Float(value))) => Some(Number::Float(value)),
        _ => None,
    }
}

pub fn number_to_term(number: Number) -> Term {
    match number {
        Number::Integer(value) => Term::Choice(Choice::Constant(Constant::Integer(value))),
        Number::Float(value) => Term::Choice(Choice::Constant(Constant::Float(value))),
    }
}

#[cfg(test)]
// These tests were generated by ChatGPT.
mod tests {
    use super::{Number, number_to_term, parse_input_term, term_to_number};
    use crate::fmc_core::{Choice, Term, choice::Constant};

    #[test]
    fn parses_boolean_and_integer_input_terms() {
        assert_eq!(
            parse_input_term("true"),
            Some(Term::Choice(Choice::Constant(Constant::Boolean(true))))
        );
        assert_eq!(
            parse_input_term("false"),
            Some(Term::Choice(Choice::Constant(Constant::Boolean(false))))
        );
        assert_eq!(
            parse_input_term("42"),
            Some(Term::Choice(Choice::Constant(Constant::Integer(42))))
        );
    }

    #[test]
    fn trims_whitespace_and_rejects_invalid_input() {
        assert_eq!(
            parse_input_term("  -7 \n"),
            Some(Term::Choice(Choice::Constant(Constant::Integer(-7))))
        );
        assert_eq!(parse_input_term("hello"), None);
        assert_eq!(parse_input_term(""), None);
    }

    #[test]
    fn converts_between_numeric_terms_and_runtime_numbers() {
        assert_eq!(
            term_to_number(Term::Choice(Choice::Constant(Constant::Integer(3)))),
            Some(Number::Integer(3))
        );
        assert_eq!(
            term_to_number(Term::Choice(Choice::Constant(Constant::Float(1.5)))),
            Some(Number::Float(1.5))
        );
        assert_eq!(
            number_to_term(Number::Float(2.25)),
            Term::Choice(Choice::Constant(Constant::Float(2.25)))
        );
    }
}
