use std::fmt::Display;

use crate::fmc_core::Term;

#[derive(Clone, PartialEq, Debug)]
/// Represents the branches of computation, similar to exceptions or exit codes.
pub enum Choice {
    Constant(Constant),
    Exception(Exception),
}

#[derive(Clone, PartialEq, Debug)]
pub enum Constant {
    Boolean(bool),
    Integer(i32),
    Float(f32),
}

#[derive(Clone, PartialEq, Debug)]
pub enum Exception {
    Skip,
    Exception(String),
    Break,
    Return,
}

impl Display for Choice {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Choice::Constant(c) => match c {
                Constant::Boolean(true) => write!(f, "true"),
                Constant::Boolean(false) => write!(f, "false"),
                Constant::Integer(i) => write!(f, "{i}"),
                Constant::Float(fl) => write!(f, "{fl}"),
            },
            Choice::Exception(e) => match e {
                Exception::Skip => write!(f, "#"),
                Exception::Exception(name) => write!(f, "{name}"),
                Exception::Break => write!(f, "break"),
                Exception::Return => write!(f, "return"),
            },
        }
    }
}

impl Choice {
    pub fn skip() -> Choice {
        Choice::Exception(Exception::Skip)
    }

    pub fn as_term(self) -> Term {
        Term::Choice(self)
    }
}

#[cfg(test)]
// These tests were generated by ChatGPT.
mod tests {
    use super::{Choice, Constant};
    use crate::fmc_core::Term;

    #[test]
    fn as_term_wraps_choice_in_term_variant() {
        let choice = Choice::Constant(Constant::Integer(7));

        assert_eq!(choice.clone().as_term(), Term::Choice(choice));
    }
}
