use clap::Parser;
use Lithe::interpreter::Interpreter;
use Lithe::machines::machine::{MachineType, StepResult};
use miette::{IntoDiagnostic, Result, WrapErr, miette};
use std::fs::File;
use std::io::{BufRead, BufReader};

#[derive(Debug, Parser)]
#[command(version)]
#[command(about = "An interpreter for Lithe", long_about = None)]
struct Cli {
    /// The path of the file to run
    path: std::path::PathBuf,

    #[command(flatten)]
    verbosity: clap_verbosity_flag::Verbosity,

    /// Use the Krivine machine
    #[arg(short, long)]
    krivine: bool,

    /// Output the machine trace
    #[arg(short, long)]
    trace: bool,

    /// Beta reduce before running
    #[arg(short, long)]
    optimise: bool,

    /// Include the rnd functions
    #[arg(long)]
    rnd: bool,
}

fn main() -> Result<()> {
    let args = Cli::parse();

    let f = File::open(&args.path)
        .into_diagnostic()
        .wrap_err_with(|| format!("could not read file `{}`", args.path.display()))?;

    let reader = BufReader::new(f);

    let lines: Vec<String> = reader
        .lines()
        .map(|line| line.into_diagnostic().wrap_err("failed to read line"))
        .collect::<Result<_>>()?;

    let program = lines.join("\n");

    let lithe = Interpreter::new(
        false,
        if args.krivine {
            MachineType::Krivine
        } else {
            MachineType::Stack
        },
    );

    let result = lithe
        .interpret(program, args.optimise, args.trace, args.rnd)
        .map_err(|error| miette!("{error}"))?;

    if result == StepResult::Failure {
        println!("Failure")
    }

    Ok(())
}

// These tests were generated by ChatGPT.
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn assignment_compile() {
        let lithe = Interpreter::new(true, MachineType::Stack);

        let _ = lithe
            .compile(
                "
            a := 5 ;
            b := 3 ;
            "
                .to_string(),
                false,
                false,
            )
            .unwrap();
    }

    #[test]
    fn basic_program() {
        let lithe = Interpreter::new(true, MachineType::Stack);
        let term = lithe
            .compile(
                "
            a := 5 ;
            while ($a > 0) {
                print $a;

                a := $a - 1;
            }
            "
                .to_string(),
                false,
                false,
            )
            .unwrap();
        println!("{}:?", term);
        lithe.run(term, false);
    }

    #[test]
    fn advanced_program() {
        let lithe = Interpreter::new(true, MachineType::Stack);
        let term = lithe
            .compile(
                "
            a := 5 ;
            if ($a > 3) {
                print true;
            } else {
                print false;
            }
            "
                .to_string(),
                false,
                false,
            )
            .unwrap();
        println!("{}:?", term);
        lithe.run(term, false);
    }
}
